### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by agronomofiorentini** [EcoDynIZW/imageseg#1]
Dear creator,
I have tried to install the package by using remotes R procedure but i have got the follow problem

```
√  checking for file 'C:\Users\Fiorentini\AppData\Local\Temp\RtmpeuGFE1\remotes1b64158335a6\EcoDynIZW-imageseg-388d34b/DESCRIPTION' ... 
-  preparing 'imageseg':
√  checking DESCRIPTION meta-information ... 
-  installing the package to process help pages
-  saving partial Rd database (6.7s)
   Errore in loadVignetteBuilder(pkgdir, TRUE) : 
     vignette builder 'R.rsp' not found
   Esecuzione interrotta
Error: Failed to install 'imageseg' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
```

**Comment by jniedballa** [comment]
Hi, 
imageseg uses static (pre-built) vignettes, which require the package "R.rsp" to install correctly. You are right, this should be mentioned. I just amended the readme. Please 
`install.packages(R.rsp)`
then try installing imageseg again. 
Best regards,

**Comment by agronomofiorentini** [comment]
after install the R.rsp package the installation procedure it is working perfectly now.

**Comment by jniedballa** [comment]
Great, thank you for the information. If there are more problems please feel free to open another issue.
